name: Build and Push Executor Image

on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile.executor'
      - 'src/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.gitea/workflows/build-executor.yml'

jobs:
  build:
    runs-on: docker
    env:
      DOCKER_BUILDKIT: 0
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Gitea container registry
        run: echo "${{ gitea.token }}" | docker login code.klsll.com -u ${{ gitea.actor }} --password-stdin

      - name: Build executor image
        run: |
          docker build \
            -f Dockerfile.executor \
            -t code.klsll.com/havartibard/chiffon-executor:latest \
            -t code.klsll.com/havartibard/chiffon-executor:${{ gitea.sha }} \
            .

      - name: Push executor image
        run: |
          docker push code.klsll.com/havartibard/chiffon-executor:latest
          docker push code.klsll.com/havartibard/chiffon-executor:${{ gitea.sha }}

